In [3]:
!pip install pymysql
import pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 2.7 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [4]:
import pandas as pd
df=pd.read_csv('cleaned_amazon_data.csv')

In [6]:
df.columns

Index(['transaction_id', 'order_date', 'customer_id', 'product_id',
       'product_name', 'category', 'subcategory', 'brand',
       'original_price_inr', 'discount_percent', 'discounted_price_inr',
       'quantity', 'subtotal_inr', 'delivery_charges', 'final_amount_inr',
       'customer_city', 'customer_state', 'customer_tier',
       'customer_spending_tier', 'customer_age_group', 'payment_method',
       'delivery_days', 'delivery_type', 'is_prime_member', 'is_festival_sale',
       'customer_rating', 'return_status', 'order_month', 'order_year',
       'order_quarter', 'product_weight_kg', 'is_prime_eligible',
       'product_rating', 'payment_method_simplified'],
      dtype='object')

In [12]:
product_details=df[['product_id','product_name','category','subcategory','brand']]

In [15]:
price=df[['original_price_inr','discount_percent','discounted_price_inr','quantity','subtotal_inr','delivery_charges','final_amount_inr']]

In [17]:
connect=pymysql.connect(
    host='localhost',
    user='root',
    password='aiktc@1234',
    database='amazon'
)

cursor=connect.cursor()
cursor

OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")